---

- name: Check requirements
  hosts: localhost
  connection: local
  roles:
    - requirements-check

- name: Deploy AWX to minikube
  hosts: target
  vars:
    exposed_node_port: 30080
    install_container: "podman" # or "docker"
  roles:
    - podman-runtime
    - docker-runtime
    - minikube-cluster
    - awx-operator
