---
- name: Ensure Memory cgroup is enabled
  ansible.builtin.stat:
    path: /sys/fs/cgroup/memory
  become: true

- name: Get latest Minikube rpm package
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    dest: "{{ minikube_download_directory }}/minikube-latest.x86_64.rpm"
    mode: "0755"

- name: Install Minikube rpm package
  ansible.builtin.dnf:
    name: "{{ minikube_download_directory }}/minikube-latest.x86_64.rpm"
    state: present
    disable_gpg_check: true
  become: true
