---
- name: Block when RedHat System
  when: ansible_os_family == "Debian"
  become: true
  block:
    - name: Ensure Memory cgroup is enabled
      ansible.builtin.stat:
        path: /sys/fs/cgroup/memory

    - name: Get latest Minikube Debian package
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        dest: "{{ minikube_download_directory }}/minikube_latest_amd64.deb"
        mode: "0755"

    - name: Install Minikube Debian package
      ansible.builtin.apt:
        deb: "{{ minikube_download_directory }}/minikube_latest_amd64.deb"
        state: present

- name: Block when RedHat System
  when: ansible_os_family == "RedHat"
  become: true
  block:
    - name: Ensure Memory cgroup is enabled
      ansible.builtin.stat:
        path: /sys/fs/cgroup/memory

    - name: Get latest Minikube rpm package
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
        dest: "{{ minikube_download_directory }}/minikube-latest.x86_64.rpm"
        mode: "0755"

    - name: Install Minikube rpm package
      ansible.builtin.dnf:
        name: "{{ minikube_download_directory }}/minikube-latest.x86_64.rpm"
        state: present
        disable_gpg_check: true
