---
# Kubectl is already part of the minikube installation, creating an alias for easier usage
- name: Create alias for kubectl
  ansible.builtin.template:
    src: kubectl-alias-binary.j2
    dest: /usr/local/bin/kubectl
    mode: "0755"
  become: true
