---
- ansible.builtin.import_tasks: install-minikube.yml # noqa name[missing]
  tags:
    - install
    - minikube

- ansible.builtin.import_tasks: start-minikube.yml # noqa name[missing]
  tags:
    - start
    - minikube

- ansible.builtin.import_tasks: kubectl.yml # noqa name[missing]
  tags:
    - kubectl
    - minikube
