---
- ansible.builtin.import_tasks: install-minikube.yml # noqa name[missing]
  tags:
    - install
    - minikube

- ansible.builtin.import_tasks: start-minikube.yml # noqa name[missing]
  tags:
    - start
    - minikube

- ansible.builtin.import_tasks: kubectl.yml # noqa name[missing]
  tags:
    - kubectl
    - minikube

- ansible.builtin.import_tasks: delete-minikube-cluster.yml # noqa name[missing]
  when: '"delete-minikube" in ansible_run_tags'
  tags:
    - delete-minikube
