---
- name: Get minikube status
  ansible.builtin.command:
    cmd: minikube status
  register: minikube_status
  changed_when: false
  failed_when: false

- name: Start minikube  # noqa no-changed-when
  ansible.builtin.command:
    cmd: minikube start {{ minikube_additional_start_parameter }}
  async: 600
  poll: 0
  register: minikube_start
  when: minikube_status.rc != 0

- name: Wait for fully started minikube instance (timeout set to 10 minutes) # noqa args[module]
  ansible.builtin.async_status:
    jid: '{{ minikube_start.ansible_job_id }}'
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 10
  when:
    - minikube_start is defined
    - minikube_start.ansible_job_id is defined

- name: Ensure minikube instance is running
  ansible.builtin.command:
    cmd: minikube status -o json
  register: minikube_status
  changed_when: false
  failed_when:
    - minikube_status.rc != 0
    - (minikube_status.stdout | from_json).APIServer != "Running"
    - (minikube_status.stdout | from_json).Host != "Running"
    - (minikube_status.stdout | from_json).Kubeconfig != "Configured"
    - (minikube_status.stdout | from_json).Kubelet != "Running"
