---

- name: Deploy AWX instance
  kubernetes.core.k8s:
    namespace: "{{ awx_namespace }}"
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: "{{ awx_instance_name }}"
      spec:
        service_type: nodeport
    state: present

- name: Wait for running state of AWX deployment (timeout set to 10 minutes)
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: "{{ awx_namespace }}"
    name: "{{ awx_instance_name }}-web"
    wait: true
    wait_sleep: 10
    wait_timeout: 600

- name: Expose port {{ exposed_node_port }}
  kubernetes.core.k8s_service:
    namespace: "{{ awx_namespace }}"
    name: "{{ awx_instance_name }}-service"
    type: NodePort
    ports:
      - port: 80
        target_port: 80
        nodePort: "{{ exposed_node_port }}"
    selector:
      app.kubernetes.io/component: awx
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/name: "{{ awx_instance_name }}-web"
    state: present

- name: Wait for availability of AWX UI (timeout set to 2 minutes)
  ansible.builtin.uri:
    url: http://{{ ansible_default_ipv4.address }}:{{ exposed_node_port }}
  register: awx_ui_availability
  until: awx_ui_availability.status == 200
  retries: 12
  delay: 10

- name: Get AWX admin secret
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: "{{ awx_namespace }}"
    name: "{{ awx_instance_name }}-admin-password"
  register: admin_secret

- name: Output login info
  ansible.builtin.debug:
    msg: |
      AWX UI is available at 'http://{{ ansible_default_ipv4.address }}:{{ exposed_node_port }}'
      Login with username 'admin' and password '{{ admin_secret['resources'][0]['data']['password'] | b64decode }}'
