---
- name: Install Python package manager
  ansible.builtin.package:
    name:
      - python3-pip
      - git
    state: present
  become: true

- name: Install Python dependencies for Ansible modules
  ansible.builtin.pip:
    name: kubernetes
    extra_args: --user
