---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true
    state: present
  become: true

- name: Store Docker GPG key in /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg  # noqa command-instead-of-module
    creates: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg
  become: true

- name: Add Docker stable repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  become: true

- name: Install Docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true
  notify: Reset_ssh_connection_handler

- name: Run handlers
  ansible.builtin.meta: flush_handlers
