---

- name: Ensure Memory cgroup is enabled
  ansible.builtin.stat:
    path: /sys/fs/cgroup/memory
  become: true

- name: Get latest Minikube Debian package
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
    dest: "{{ minikube_download_directory }}/minikube_latest_amd64.deb"
    mode: '0755'

- name: Install Minikube Debian package
  ansible.builtin.apt:
    deb: "{{ minikube_download_directory }}/minikube_latest_amd64.deb"
    state: present
  become: true
